### ISSUE TITLE
My mind isn't blown...

### ISSUE THREAD

**Issue by AngeloYoun** [plhnk/liferay-sketch-library#1]
The description for this project is misleading. My mind was not blown. Advertising false expectations makes me feel bad.

**Comment by plhnk** [comment]
Not able to reproduce issue–could be your small mind is incapable of fathoming the pain we have felt these many years.

**Comment by AngeloYoun** [comment]
<img width="856" alt="screen shot 2016-08-19 at 5 02 20 pm" src="https://cloud.githubusercontent.com/assets/11049786/17827267/b83fd3ee-662e-11e6-9c46-0bd7271790f2.png">
Nice contributions bro
